from abc import ABC, abstractmethod
from typing import Callable, Awaitable, Optional

class IConversationProvider(ABC):
    """
    Interface for speech-to-speech LLM providers (e.g., Gemini Live API).
    """

    @abstractmethod
    async def start_session(
        self, 
        session_id: str, 
        system_instruction: str, 
        voice_name: str
    ) -> None:
        """Initializes and starts the session with the AI provider."""
        pass

    @abstractmethod
    async def send_audio(self, audio_chunk: bytes) -> None:
        """Sends a raw audio chunk (PCM) from the user's microphone."""
        pass

    @abstractmethod
    async def send_text(self, text: str) -> None:
        """Sends a text message or instruction to the provider."""
        pass

    @abstractmethod
    async def update_system_instruction(self, instruction: str) -> None:
        """Dynamically updates system instructions to steer the conversation."""
        pass

    @abstractmethod
    async def close(self) -> None:
        """Cleans up and closes the connection to the provider."""
        pass

    @abstractmethod
    def register_audio_handler(self, callback: Callable[[bytes], Awaitable[None]]) -> None:
        """Registers a callback for output audio chunks generated by the AI."""
        pass

    @abstractmethod
    def register_text_handler(self, callback: Callable[[str, bool], Awaitable[None]]) -> None:
        """Registers a callback for text transcripts (content, is_final)."""
        pass

    @abstractmethod
    def register_interruption_handler(self, callback: Callable[[], Awaitable[None]]) -> None:
        """Registers a callback to execute when the user interrupts the assistant."""
        pass

    @abstractmethod
    def register_turn_handler(self, callback: Callable[[Optional[str]], Awaitable[None]]) -> None:
        """Registers a callback for when the turn transitions (user finishes, or AI finishes)."""
        pass
